name: Export to Invited Remote

on:
  push:
    branches: [main]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Build and Export Kobweb site
        run: ./gradlew kobwebExport

      - name: Copy Exported Site to temp folder
        run: |
          mkdir export
          cp -r site/.kobweb/site/* export/

      - name: Create orphan branch for static files
        run: |
          git checkout --orphan release-temp
          git rm -rf .
          cp -r export/* .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Export Kobweb static site"

      - name: Push to 'release' branch on 'invited' remote
        run: |
          git remote add invited https://x-access-token:${{ secrets.INVITED_PAT }}@github.com/<your-org-or-username>/<repo-name>.git
          git push -f invited HEAD:release
