name: Export Static Site to Release Branch

on:
  push:
    branches: [main]

jobs:
  export:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy Exported Files to Temporary Folder
        run: |
          mkdir export
          cp -r site/.kobweb/site/* export/

      - name: Create orphan release branch
        run: |
          git checkout --orphan release-temp
          git rm -rf .
          cp -r export/* .
          rm -rf export
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy static site from main"

      - name: Push to release branch using GITHUB_TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push -f origin HEAD:release
