name: Export Static Site to Release Branch

on:
  push:
    branches: [main]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy Exported Files to Temporary Folder
        run: |
          mkdir export
          cp -r site/.kobweb/site/* export/

      - name: Create orphan release branch
        run: |
          git checkout --orphan release-temp
          git rm -rf .
          cp -r export/* .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy static site from main"

      - name: Push to release branch
        run: |
          git push -f origin HEAD:release
