name: Export Kobweb Static Site to Release Branch

on:
  push:
    branches: [main]  # Trigger only when main is updated

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Build and Export Kobweb site
        run: ./gradlew :site:kobwebExport

      - name: Copy Exported Site to temporary folder
        run: |
          mkdir export
          cp -r site/.kobweb/site/* export/

      - name: Create orphan branch and commit static files
        run: |
          git checkout --orphan release-temp
          git rm -rf .
          cp -r export/* .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Export Kobweb static site"

      - name: Force push to release branch on origin
        run: |
          git push -f origin HEAD:release
